// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWoVtlxl9tiTmbmu2Z8GUxS-wKGLKfpc',
    appId: '1:527764595355:web:615c329a9cab160d639c3e',
    messagingSenderId: '527764595355',
    projectId: 'firelogin-river',
    authDomain: 'firelogin-river.firebaseapp.com',
    storageBucket: 'firelogin-river.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SENfPm4auFFq0PvMdVaH0wkSEzCLwf4',
    appId: '1:527764595355:android:9903efd28dac8f61639c3e',
    messagingSenderId: '527764595355',
    projectId: 'firelogin-river',
    storageBucket: 'firelogin-river.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGD8ktlk5426QausoUPFn9NmbBhR1nUOA',
    appId: '1:527764595355:ios:17af486c0f278b9d639c3e',
    messagingSenderId: '527764595355',
    projectId: 'firelogin-river',
    storageBucket: 'firelogin-river.appspot.com',
    iosClientId: '527764595355-7ta93k583snhg4u08edij9pk1bkrgk99.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRiverpod',
  );
}
